# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_production
  pool: 5
  username: jenn
  password: jenn12

development:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_development
  pool: 5
  username: jenn
  password: jenn12

test:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_test
  pool: 5
  username: jenn
  password: jenn12
